FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --chown=app:app publish/emulator .
RUN mkdir -p presets && chown app:app presets
USER app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Wintime.Control.Emulator.dll"]
